import assert from "node:assert/strict";
import test from "node:test";
import { createApp } from "../server.mjs";
import { MemoryStore } from "../lib/db.mjs";

const config = { publicBaseUrl: "", sessionSecret: "a-secure-test-secret-that-is-long-enough-123", happ: { providerId: "euvlYGyS", authKey: "x" }, threeXui: { baseUrl: "https://xui.example", username: "u", password: "p", inboundIds: [1, 2] } };

function mocks() {
  return {
    threeXui: {
      async addClient() {}, async getSubscriptionUrl() { return "https://xui.example/sub/user"; }, async traffic() { return { obj: { up: 1024, down: 2048 } }; }, async getClient() { return { obj: { client: { email: "saved", enable: true } } }; }, async updateClient() {}, async deleteClient() {}, async onlineClients() { return { obj: [] }; }
    },
    happ: { async createInstallLink() { return { id: 7, install_code: "install-code" }; }, async listHwid() { return { obj: [{ hwid: "hw-1", os: "iOS" }] }; }, async deleteHwid() {}, async updateInstall() {}, async listDomains() { return { obj: [] }; } },
    fetchImpl: async (url) => url.includes("xui.example/sub/user") ? new Response("vless://personal-server", { headers: { "content-type": "text/plain" } }) : new Response("", { status: 404 })
  };
}

async function running() { const store = new MemoryStore(); await store.init(); const app = createApp({ config, store, ...mocks() }); await new Promise((resolve) => app.listen(0, "127.0.0.1", resolve)); return { app, base: `http://127.0.0.1:${app.address().port}` }; }
function cookies(response) { return response.headers.get("set-cookie").split(/, (?=[a-z]+=)/i).map((part) => part.split(";")[0]).join("; "); }
function csrfFrom(cookieHeader) { return cookieHeader.match(/csrf=([^;]+)/)?.[1] || ""; }

test("health endpoint is public and does not touch the database", async () => { const { app, base } = await running(); try { const response = await fetch(`${base}/healthz`); assert.equal(response.status, 204); } finally { await new Promise((resolve) => app.close(resolve)); } });

test("admin login requires changing the default password", async () => { const { app, base } = await running(); try { const login = await fetch(`${base}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username: "admin", password: "admin" }) }); assert.equal(login.status, 200); assert.equal((await login.json()).mustChangePassword, true); const jar = cookies(login); const changed = await fetch(`${base}/api/auth/change-password`, { method: "POST", headers: { "content-type": "application/json", cookie: jar, "x-csrf-token": csrfFrom(jar) }, body: JSON.stringify({ password: "new-secure-password" }) }); assert.equal(changed.status, 200); } finally { await new Promise((resolve) => app.close(resolve)); } });

test("subscription creation provisions a client and public endpoint adds Happ metadata", async () => { const { app, base } = await running(); try { const login = await fetch(`${base}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username: "admin", password: "admin" }) }); const jar = cookies(login); await fetch(`${base}/api/auth/change-password`, { method: "POST", headers: { "content-type": "application/json", cookie: jar, "x-csrf-token": csrfFrom(jar) }, body: JSON.stringify({ password: "new-secure-password" }) }); const create = await fetch(`${base}/api/subscriptions`, { method: "POST", headers: { "content-type": "application/json", cookie: jar, "x-csrf-token": csrfFrom(jar) }, body: JSON.stringify({ name: "Graphite VPN", description: "Персональный доступ", trafficUnlimited: false, trafficGb: 10, daysUnlimited: false, days: 30, devicesUnlimited: false, deviceLimit: 2, ipUnlimited: false, ipLimit: 2, resetPeriod: "never", supportUrl: "https://example.com/support" }) }); assert.equal(create.status, 201); const created = await create.json(); const publicResponse = await fetch(created.url); assert.equal(publicResponse.status, 200); assert.equal(await publicResponse.text(), "vless://personal-server"); assert.equal(publicResponse.headers.get("profile-title"), "Graphite VPN"); assert.match(publicResponse.headers.get("subscription-userinfo"), /total=/); assert.equal((await fetch(`${base}/s/nope`)).status, 404); } finally { await new Promise((resolve) => app.close(resolve)); } });

test("simple mode works with only a legacy upstream URL and no 3x-ui credentials", async () => { const store = new MemoryStore(); await store.init(); const simpleConfig = { ...config, threeXui: { baseUrl: "", username: "", password: "", inboundIds: [] }, happ: { providerId: "euvlYGyS", authKey: "" }, legacyUpstreamUrl: "https://source.example/sub" }; const app = createApp({ config: simpleConfig, store, fetchImpl: async (url) => url === simpleConfig.legacyUpstreamUrl ? new Response("vless://shared-server", { headers: { "content-type": "text/plain" } }) : new Response("", { status: 404 }) }); await new Promise((resolve) => app.listen(0, "127.0.0.1", resolve)); try { const base = `http://127.0.0.1:${app.address().port}`; const login = await fetch(`${base}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username: "admin", password: "admin" }) }); const jar = cookies(login); await fetch(`${base}/api/auth/change-password`, { method: "POST", headers: { "content-type": "application/json", cookie: jar, "x-csrf-token": csrfFrom(jar) }, body: JSON.stringify({ password: "new-secure-password" }) }); const create = await fetch(`${base}/api/subscriptions`, { method: "POST", headers: { "content-type": "application/json", cookie: jar, "x-csrf-token": csrfFrom(jar) }, body: JSON.stringify({ name: "Simple VPN", description: "Общий каталог", trafficUnlimited: true, daysUnlimited: true, devicesUnlimited: true, ipUnlimited: true, resetPeriod: "never", supportUrl: "" }) }); assert.equal(create.status, 201); const publicResponse = await fetch((await create.json()).url); assert.equal(publicResponse.status, 200); assert.equal(await publicResponse.text(), "vless://shared-server"); } finally { await new Promise((resolve) => app.close(resolve)); } });

test("simple mode creates a Happ limited link and synchronizes HWID devices", async () => { const store = new MemoryStore(); await store.init(); const calls = []; const simpleConfig = { ...config, threeXui: { baseUrl: "", username: "", password: "", inboundIds: [] }, happ: { providerId: "euvlYGyS", authKey: "12345678901234567890123456789012" }, legacyUpstreamUrl: "https://source.example/sub" }; const app = createApp({ config: simpleConfig, store, happ: { async createInstallLink(limit) { calls.push(["create", limit]); return { id: 9, install_code: "INSTALL123456" }; }, async listHwid() { return { data: [{ hwid: "hw-1", device_name: "Android" }] }; }, async updateInstall(...args) { calls.push(["update", ...args]); }, async deleteHwid() {} }, fetchImpl: async (url) => url === simpleConfig.legacyUpstreamUrl ? new Response("vless://shared-server", { headers: { "content-type": "text/plain" } }) : new Response("", { status: 404 }) }); await new Promise((resolve) => app.listen(0, "127.0.0.1", resolve)); try { const base = `http://127.0.0.1:${app.address().port}`; const login = await fetch(`${base}/api/auth/login`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username: "admin", password: "admin" }) }); const jar = cookies(login); await fetch(`${base}/api/auth/change-password`, { method: "POST", headers: { "content-type": "application/json", cookie: jar, "x-csrf-token": csrfFrom(jar) }, body: JSON.stringify({ password: "new-secure-password" }) }); const create = await fetch(`${base}/api/subscriptions`, { method: "POST", headers: { "content-type": "application/json", cookie: jar, "x-csrf-token": csrfFrom(jar) }, body: JSON.stringify({ name: "Limited VPN", description: "Лимит устройств", trafficUnlimited: false, trafficGb: 20, daysUnlimited: false, days: 30, devicesUnlimited: false, deviceLimit: 2, ipUnlimited: true, resetPeriod: "never", supportUrl: "" }) }); assert.equal(create.status, 201); const created = await create.json(); assert.match(created.url, /installid=INSTALL123456/i); const detail = await fetch(`${base}/api/subscriptions/${created.subscription.id}`, { headers: { cookie: jar } }); assert.equal((await detail.json()).devices[0].hwid, "hw-1"); assert.deepEqual(calls[0], ["create", 2]); } finally { await new Promise((resolve) => app.close(resolve)); } });
