export const DARK_THEME = {
  backgroundColors: ["#080A0DFF", "#11151AFF", "#1A2026FF"],
  backgroundGradientRotationAngle: 0,
  backgroundGradientColorIntensity: 1,
  backgroundImageType: "system",
  buttonImageType: "light",
  buttonColor: "#3A4652FF",
  buttonTextColor: "#FFFFFFFF",
  buttonTimerColor: "#FFFFFFFF",
  powerIconColor: "#0D1115FF",
  serverRowBackgroundColor: "#182027CC",
  serverRowTitleTextColor: "#F4F7FAFF",
  serverRowSubTitleTextColor: "#AAB5BFFF",
  serverRowChevronColor: "#DCE3E9FF",
  selectedServerRowColor: "#2C3944E6",
  subsHeaderColor: "#12171CFF",
  subscriptionInfoBackgroundColor: "#10161BFF",
  subscriptionInfoTextColor: "#F4F7FAFF",
  subscriptionTrafficBackgroundColor: "#293741FF",
  disclosureHeaderTextColor: "#F4F7FAFF",
  disclosureSubHeaderTextColor: "#AAB5BFFF",
  topBarButtonsColor: "#E1E8EEFF",
  supportIconColor: "#AFC2D2FF",
  profileWebPageIconColor: "#AFC2D2FF",
  subHeaderButtonColor: "#D3E0EAFF",
  additionalOptionsButtonColor: "#D3E0EA99",
  settingsControlsTintColor: "#AFC2D2FF",
  elipseColors: ["#BFD0DC99", "#71839199", "#3A465299"]
};
